#!/usr/bin/env bash
#commands to install nginx

sudo apt-get update
sudo apt-get install nginx
sudo ufw 'Nginx HTTP'

echo "Hello World!" | sudo tee /var/ww/html/index.html

# testing nginx config
sudo nginx -t

sudo service nginx reload
